config/routes.rb
Rails.application.routes.draw do
  #ActiveAdmin 관련 오류로 수정함
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "home#index"
  resources :users
  
  namespace :api do
    post 'users/sign_in', to: 'authentication#create'
    post 'users/sign_up', to: 'users#create'
    post 'users/like', to: 'likes#toggle'
    post "/kakaocert/requestESign", to: 'kakaocert#requestESign'
    get "/kakaocert/getESignState", to: 'kakaocert#getESignState'
    get "/kakaocert/verifyESign", to: 'kakaocert#verifyESign'
    
    resources :users, only: %i(index show update) do
      resources :likes, only: %i(index)
      collection do
        get :mypage
        get :keyword
        post :keyword
        post :email_auth
        post :sms_auth
        post :add_device
        post :remove_device
        post :find
        delete :withdrawal
        delete :keyword
        put :reset
        put :range
      end
      member do
        get :list
      end
    end
    
    resources :posts do
      member do
        get :like
        get :booking
      end
    end
    
    resources :chats do
      resources :messages, only: %i(index create)  
      get :count, on: :collection
    end
    
    resources :image, only: %i(create destroy)
    
    resources :locations, only: %i(index show) do
      put :certificate, on: :collection
      get :display, on: :collection
    end
    resources :bookings, only: %i(index new show create destroy) do
      put :complete, on: :member
      put :accept, on: :member
    end
  
    resources :companies, only: %i(show create destroy) do
      patch :confirm, on: :member
    end
  
    resources :reports, only: %i(index create)
    resources :questions, only: %i(create)
    resources :reviews, only: %i(index create update destroy)
    resources :pages, only: %i(show)
  end

  resources :posts
end

app/views/shared/_alert_banner.html.erb
<div class="alert alert-danger">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_header.html.erb
<header id="fixed-bar" class="fixed-bar-box-shadow">
  <div id="fixed-bar-wrap">
    <h1 id="fixed-bar-logo-title">
      <a href="<%= root_path %>">
        <img class="fixed-logo" alt="모두나눔" src="/image/default.png">
        <span class="fixed-title">모두나눔
          <span class="sub-title">위치 기반 C2C 공유 플랫폼</span>
        </span>
      </a>
    </h1>

    <section id="fixed-bar-download">
      <a class="fixed-download-button btn-modal" id="header-download-button-ios" href="#" onclick="return false;" data-name="sign-in">
        <i class="fas fa-lock"></i>
        <div class="fixed-download-text">로그인</div>
      </a>
      <a class="fixed-download-button" id="header-download-button-android" href="<%= posts_path %>">
        <img class="fixed-apple-store" alt="App Store" src="/image/icon/app-store-brands.svg">
        <div class="fixed-download-text">다운로드</div>
      </a>
    </section>
  </div>
</header>

app/views/shared/_notice_banner.html.erb
<div class="alert alert-success">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_post.html.erb
<div class="col-lg-3 col-md-4 col-sm-6 mb-3">
<%= link_to post do %>
  <div class="card">
      <img src="<%= post.image.url(:square) if post.image? %>" class="card-img-top img-thumbnail" alt="No Image">
    <div class="card-body">
      <div class="text-center">
        <span class="text"><strong><%= number_with_delimiter post.price %></strong> 원</span>
        <p class="card-title"><%= post.title.truncate(15) %></p>
      </div>
      <hr>
      <small>
        <p class="card-text post-description"><%= post.body %></p>
        <hr>
        <div class="card-subtitle text-right">
          판매자: <%= post.user&.name %> <br>
          조회수: <%= number_with_delimiter post.like_count %> 회
        </div>
      </small>
    </div>
    <% end %>
    <div class="card-footer py-2 pr-3">
      <small class="float-right">
        <span class= "mr-1">
          <i class="fas fa-wallet mr-1"></i>
          <%#= item.line_items.sum("amount") %>
        </span>
        <span class= "mr-1">
          <i class="<%= current_user&.has_item?(item) ? 'fas fa-heart text-danger' : 'far fa-heart' %> mr-1"></i>
          <span id = "likecount"><%#= item.user_items.size %></span>
        </span>
        <span>
          <i class="fas fa-comment-alt mr-1"></i>
          <%#= item.comments.size %>
        </span>
      </small>
    </div>
  </div>
</div>

app/views/shared/alert.html.erb
<div class="container">
  <div class="justify-content-center text-center">
    <img src="/image/kakao_login.png" alt="" class="image">
    <div class="title">카카오 로그인이 완료되었습니다!</div>
    <div class="body">잠시만 기다려주세요...</div>
  </div>
</div>

<script>
  setTimeout(() => {
    window.ReactiNativeWebView.postMessage("<%= @result %>");
    console.log("Send postMessage.")
  }, 1000);
</script>

<style>
.container {
  height:100vh;
}

.image {
  padding-top: 25vh;
  width: 70%;
}

.title {
  padding-top: 5vh;
  font-size: 4em;
  line-height: 1;
  margin-bottom: 0.7em;
  font-weight: 700;
}

.body {
  font-size: 3em;
  line-height: 1;
  margin-bottom: 0.5em;
}

</style>

app/views/shared/apple_login.html.erb
<div class="callback">
  <div class="container">
    <div class="justify-content-center text-center">
      <img src="/image/apple_login.png" alt="" class="image">
      <div class="title">Apple 로그인이 완료되었습니다!</div>
      <div class="body">잠시만 기다려주세요...</div>
    </div>
  </div>
</div>

<script>
  setTimeout(() => {
    window.ReactNativeWebView.postMessage("{\"token\":\"<%= @token %>\", \"id\":\"<%= @user.id %>\", \"location_auth\":\"<%= @user.is_location_auth? ? @user.location.title : nil %>\"}", "*");
    console.log("Send postMessage.")
  }, 1000);
</script>

app/views/shared/error.html.erb
<div class="callback">
  <div class="container">
    <div class="justify-content-center text-center">
      <img src="/image/default.png" alt="" class="image">
      <div class="title">소셜 로그인 취소</div>
      <div class="body">잠시만 기다려주세요...</div>
    </div>
  </div>
</div>

<script>
  setTimeout(() => {
    window.ReactNativeWebView.postMessage("{\"error\" : \"소셜 로그인 취소\"}", "*");
    console.log("Cancel social login.")
  }, 1000);
</script>

app/views/shared/kakao_login.html.erb
<div class="callback">
  <div class="container">
    <div class="justify-content-center text-center">
      <img src="/image/kakao_login.png" alt="" class="image">
      <div class="title">카카오 로그인이 완료되었습니다!</div>
      <div class="body">잠시만 기다려주세요...</div>
    </div>
  </div>
</div>

<script>
  setTimeout(() => {
    window.ReactNativeWebView.postMessage("{\"token\":\"<%= @token %>\", \"id\":\"<%= @user.id %>\", \"location_auth\":\"<%= @user.is_location_auth? ? @user.location.title : nil %>\"}", "*");
    console.log("Send postMessage.")
  }, 1000);
</script>

app/views/shared/login.html.erb
<div class="container">
  <div class="justify-content-center text-center">
    <img src="/image/kakao_login.png" alt="" class="image">
    <div class="title">카카오 로그인이 완료되었습니다!</div>
    <div class="body">잠시만 기다려주세요...</div>
  </div>
</div>

<script>
  setTimeout(() => {
    window.ReactNativeWebView.postMessage("{\"token\":\"<%= @token %>\", \"id\":\"<%= @user.id %>\", \"location_auth\":\"<%= @user.is_location_auth? ? @user.location.title : nil %>\"}", "*");
    console.log("Send postMessage.")
  }, 1000);
</script>

<style>
.container {
  height:100vh;
}

.image {
  padding-top: 25vh;
  width: 23vh;
}

.title {
  padding-top: 5vh;
  font-size: 4em;
  line-height: 1;
  margin-bottom: 0.7em;
  font-weight: 700;
}

.body {
  font-size: 3em;
  line-height: 1;
  margin-bottom: 0.5em;
}

</style>