config/routes.rb
Rails.application.routes.draw do
  #ActiveAdmin 관련 오류로 수정함
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root "home#index"
  resources :users
  
  namespace :api do
    post 'users/sign_in', to: 'authentication#create'
    post 'users/sign_up', to: 'users#create'
    post 'users/like', to: 'likes#toggle'
    post "/kakaocert/requestESign", to: 'kakaocert#requestESign'
    get "/kakaocert/getESignState", to: 'kakaocert#getESignState'
    get "/kakaocert/verifyESign", to: 'kakaocert#verifyESign'
    
    resources :users, only: %i(index show update) do
      resources :likes, only: %i(index)
      collection do
        get :mypage
        get :keyword
        post :keyword
        post :email_auth
        post :sms_auth
        post :add_device
        post :remove_device
        post :find
        delete :withdrawal
        delete :keyword
        put :reset
        put :range
      end
      member do
        get :list
      end
    end
    
    resources :posts do
      member do
        get :like
        get :booking
      end
    end
    
    resources :chats do
      resources :messages, only: %i(index create)  
      get :count, on: :collection
    end
    
    resources :image, only: %i(create destroy)
    
    resources :locations, only: %i(index show) do
      put :certificate, on: :collection
      get :display, on: :collection
    end
    resources :bookings, only: %i(index new show create destroy) do
      put :complete, on: :member
      put :accept, on: :member
    end
  
    resources :companies, only: %i(show create destroy) do
      patch :confirm, on: :member
    end
  
    resources :reports, only: %i(index create)
    resources :questions, only: %i(create)
    resources :reviews, only: %i(index create update destroy)
    resources :pages, only: %i(show)
  end

  resources :posts
end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
    def index
      @user = User.new
    end
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section id="home-main-section-top" class="background-pale-peach">
  <div id="home-main-top">
    <div class="home-main-desc ml-4 ml-xl-0">
      <h1 class="home-main-title">우리 함께,<br>모두 나눔</h1>
      <p class="text-m">
        동네 주변에서, 필요한 물건을 찾아봐요.<br> 잘 쓰지 않는 물품, 이웃과 함께 공유해요.
      </p>
    </div>
    <div class="home-main-image-top">
      <img class="screenshot" alt="screenshot" src="/image/screenshot/main_1.png">
    </div>
  </div>
</section>
<section class="home-main-section">
  <div class="home-main-content">
    <div class="home-main-image text-left">
      <img class="screenshot ml-4 ml-xl-0" style="width: 580px; padding: 10% 0;" alt="screenshot" src="/image/screenshot/main_2.png">
    </div>
    <div class="mr-4 mr-xl-0" style="width:360px;">
      <h1 class="home-main-title pl-1">쉽고 빠른,<br>중고 대여 프로세스</h1>
      <p class="text-m pl-1">
        물품 검색부터 대여 완료까지,<br>
        모두나눔의 다양한 기능을 사용해보세요!
      </p>
        <ul class="home-story-list row">
          <li class="home-story-list-item col">
            <div class="text-s text-bold mt-2 mb-1"><i class="fas fa-search"></i> 고급 검색 기능</div>
            <div class="text-xs">이름, 카테고리, 대여횟수 등<br>필터링 기능을 사용하세요. </div>
          </li>
          <li class="home-story-list-item col">
            <div class="text-s text-bold mt-2 mb-1"><i class="fas fa-comments"></i> 실시간 채팅</div>
            <div class="text-xs">추가 물품 정보가 궁금할 땐<br>실시간 채팅을 사용하세요.</div>
          </li>
        </ul>
        <ul class="home-story-list row">
          <li class="home-story-list-item col">
            <div class="text-s text-bold mt-2 mb-1"><i class="fas fa-calendar-check"></i> 예약 내용 확인</div>
            <div class="text-xs">예약 목록 캘린더를 통해<br>신청/요청 목록을 확인해요.</div>
          </li>
          <li class="home-story-list-item col">
            <div class="text-s text-bold mt-2 mb-1"><i class="fas fa-bell"></i> 키워드 알림</div>
            <div class="text-xs">찾고 있는 물품이 없나요?<br>키워드 알림을 사용해 보세요!</div>
          </li>
        </ul>
    </div>
  </div>
</section>
<section class="home-main-section background-pale-brown">
  <div class="home-main-content home-main-reverse">
    <div class="home-main-image text-right">
      <img class="screenshot mr-4 mr-xl-0" style="padding: 5% 0;" alt="screenshot" src="/image/screenshot/main_3.png">
    </div>
    <div class="ml-4 ml-xl-0">
      <h1 class="home-main-title">전자서명으로,<br>더욱 안전하게</h1>
      <p class="text-m">
        <img class="logo" alt="screenshot" src="/image/logo/kakaocert_logo.png">를 통한<br>
        편리하고 안전한 예약 시스템
      </p>
      <div class="home-buttons">
        <a class="kakao-button text-m text-bold" href="https://www.kakaocert.com/"><img class="logo" alt="screenshot" src="/image/logo/kakaocert_logo.png">란?</a>
      </div>
    </div>
  </div>
</section>
<section class="home-main-section">
  <div class="home-main-content">
    <div class="home-main-image ml-4 ml-xl-0">
      <img class="screenshot ml-4 ml-xl-0" style="width: 630px; padding: 5% 0;" alt="screenshot" src="/image/screenshot/main_4.png">
    </div>
    <div class="mr-4 mr-xl-0">
      <h1 class="home-main-title">위치 기반<br>C2C 공유 플랫폼</h1>
      <p class="text-m">
        모두나눔의 여러 기능과 함께 <br>이웃들과 다양한 물품을 공유해 보세요!
      </p>
      <div class="home-buttons">
        <a class="home-button btn-modal text-m text-bold" href="#" onclick="return false;" data-name="info">소개 영상 보기</a>
      </div>
    </div>
  </div>
</section>

<div class="footer">
  <div class="mx-4">
    <div class="row">
      <div class="col">
        <hr class="mb-3">
      </div>
    </div>
    <div class="container pb-4">
      <div class="row mt-2">
        <div class="col-12 col-md-6 text-xxs text-secondary text-center text-md-left">
          <ul class="list-inline pb-1">
            <li class="list-inline-item text-secondary">
              <a class="py-1 text-secondary btn-modal" href="#" onclick="return false;" data-name="page" data-type="tos">이용약관</a> |
              <a class="py-1 text-secondary btn-modal" href="#" onclick="return false;" data-name="page" data-type="privacy">개인정보처리방침</a> |
              <a class="py-1 text-secondary btn-modal" href="#" onclick="return false;" data-name="page" data-type="location">위치기반서비스 이용약관</a><br>
              applePink | 사업자등록번호: 601-11-92065
            </li>
          </ul>
        </div>
        <div class="col-12 col-md-6 text-xxs text-center text-md-right">
          <p class="pb-1 text-secondary">
            파트너 문의: <a class="py-1 text-secondary" href="mailto:sakiss4774@gmail.com">sakiss4774@gmail.com</a><br>
            © 2021. applePink Co. all rights reserved.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal-sign-in 시작 -->
<div class="modal fade" id="modal-sign-in" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sign-in" role="document">
    <div class="modal-content" style="border-radius: 0.625rem;">
      <div class="modal-header" style="padding: 0.9375rem 0.9375rem;">
        <div class="text-xl text-bold">모두나눔 로그인</div>
      </div>
      <div class="modal-body text-center" style="padding: 0.9375rem 0.625rem;">
        <div class="card-body">
          <%= form_for @user, url: api_users_sign_in_path(@user), method: "POST", remote: true do |f| %>
            <div class="input-group form-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <%= f.email_field :email, placeholder: "email", class: "form-control" %>
            </div>
            <div class="input-group form-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <%= f.password_field :password, placeholder: "password", autocomplete: "off", class: "form-control" %>
            </div>
            <%= f.submit "로그인", class: "btn float-right login_btn" %>
          <% end %>
        </div>
        <div class="card-footer">
          <div class="d-flex justify-content-center links">
            Don't have an account?<a href="#">Sign Up</a>
          </div>
          <div class="d-flex justify-content-center">
            <a href="#">Forgot your password?</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- modal-sign-in 끝 -->

<!-- modal-info 시작 -->
<div class="modal fade" id="modal-info" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-video" role="document">
    <div class="modal-content" style="border-radius: 0.625rem;">
      <div class="modal-header" style="padding: 0.9375rem 0.9375rem;">
        <div class="text-xl text-bold">모두나눔 소개 영상</div>
      </div>
      <div class="modal-body text-center" style="padding: 0.9375rem 0.625rem;">
        <iframe width="1000" height="562.5" src="https://www.youtube.com/embed/Stbh5KFHQaY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<!-- modal-info 끝 -->

<!-- modal-page 시작 -->
<div class="modal fade" id="modal-page" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-page" role="document">
    <div class="modal-content" style="border-radius: 0.625rem;">
      <div class="modal-header" style="padding: 0.9375rem 0.9375rem;">
        <div class="text-bold">
          <!-- 약관 제목 -->
          <span class="page-title text-xl"></span>
          <!-- 약관 발행일 & 시행일 -->
          <span class="ml-1 text-xs">
            (발행일: <span class="page-updated_at"></span> | 시행일: <span class="page-effective_date"></span>)
          </span>
        </div>
      </div>
        <!-- 약관 내용 -->
      <div class="modal-body page-body text-xs text-dark-gray" style="padding: 0.9375rem 0.9375rem;"></div>
    </div>
  </div>
</div>
<!-- modal-page 끝 -->

<script>
const modal_sign_in = $("#modal-sign-in")
const modal_info = $("#modal-info")
const modal_page = $("#modal-page")

$(".btn-modal").on("click", function() {
  switch ($(this).data("name")) {
    case "sign-in":
      modal_sign_in.modal("show");
      break;

    case "info":
      modal_info.modal("show");
      break;

    case "page":
      Rails.ajax({
        type: "get",
        url: `/api/pages/${$(this).data("type")}`,
        dataType: "json",
        success: (data) => {
          modal_page.find(".page-title").html(data.title)
          modal_page.find(".page-body").html(simpleFormat(data.body))
          modal_page.find(".page-updated_at").html(getFormatDate(new Date(data.updated_at)))
          modal_page.find(".page-effective_date").html(getFormatDate(new Date(data.effective_date)))
          modal_page.modal("show");
        },
        error: () => {
          alert("비정상적인 요청입니다.")
        }
      });
      break;
  }
})
</script>